env: local
name: cats-social-api
port: '8080'
database:
  conMaxIdleTime: 30
  conMaxLifeTime: 60
  maxIdleCons: 20
  maxOpenCons: 20
  master:
    dbName: postgres
    host: localhost
    password: S3cret
    port: 5432
    schema: public
    user: admin
  replica:
    dbName: postgres
    host: localhost
    password: S3cret
    port: 5432
    schema: public
    user: admin